Changed incorrect message and response code
ita-social-projects/GreenCity pull request #1235
Opened 2020-08-26 14:33 UTC by Yura09

2020-08-26 16:38 UTC, MarDatsko approved these changes

2020-08-26 18:40 UTC, antonbakalets requested changes

2020-08-26 18:40 UTC, antonbakalets commented on core/src/main/java/greencity/exception/handler/CustomExceptionHandler.java
> +     * Method intercept exception {@link UserHasNoAvailableHabitDictionaryException}.
JavaDoc is mentioning `UserHasNoAvailableHabitDictionaryException`, but the annotation is mentioning `ConstraintViolationException`. So which one are you trying to handle?

2020-08-26 18:40 UTC, antonbakalets commented on core/src/main/java/greencity/repository/HabitDictionaryTranslationRepo.java
> +        + "habit_dictionary_id NOT IN "
![image](https://user-images.githubusercontent.com/3871580/91343117-b563d580-e7e4-11ea-95c6-2009b4c75aa8.png)
Is that what you are trying to achieve with this NOT IN?

2020-08-27 15:40 UTC, antonbakalets commented on core/src/main/java/greencity/exception/handler/CustomExceptionHandler.java
> +    public final ResponseEntity<Object> handleConstraintViolationException(ConstraintViolationException ex,
Now there is a new problem. `ConstraintViolationException` is a generic exception that is thrown on any validation error. So whatever is the reason user will receive `SELECT_CORRECT_LANGUAGE` message. 
Can you send instead the message extracted from `ex` object instead? 
Could you please check that my suggestions are correct?

2020-08-27 16:02 UTC, TarasDovganyuk approved these changes

2020-08-27 19:31 UTC, merged