Add base64
ita-social-projects/GreenCity pull request #1238
Opened 2020-08-27 21:37 UTC by MarDatsko

2020-08-28 15:32 UTC, vorfolomey approved these changes

2020-08-31 19:06 UTC, antonbakalets requested changes

2020-08-31 19:06 UTC, antonbakalets commented on core/src/main/java/greencity/service/impl/CloudStorageService.java
> +            return new MockMultipartFile(tempFile.getPath(), new FileInputStream(tempFile));
Please do not use classes intended for testing in main code. 

Please also change the scope of `org.springframework:spring-test` to `test `in pom.xml

2020-09-02 11:24 UTC, Yura09 approved these changes

2020-09-02 11:55 UTC, eyouu approved these changes

2020-09-03 07:54 UTC, antonbakalets approved these changes

2020-09-03 08:07 UTC, merged