Change the response to return message without the name of the function's invocation
ita-social-projects/GreenCity pull request #1241
Opened 2020-08-28 14:47 UTC by vorfolomey

2020-08-28 19:05 UTC, antonbakalets requested changes
I was waiting for this pull request.

2020-08-28 19:05 UTC, antonbakalets commented on core/src/main/java/greencity/exception/handler/CustomExceptionHandler.java
> +            .reduce("", (subTotal, element) -> subTotal + element);
Using `.reduce()` you concatenate `String`s producing a new `String` each time.
It's better to use `.collect(Collectors.joining(""));` that is designed for such cases.

2020-09-02 10:58 UTC, MarDatsko approved these changes

2020-09-02 11:04 UTC, TarasDovganyuk approved these changes

2020-09-02 11:13 UTC, eyouu approved these changes

2020-09-03 07:55 UTC, antonbakalets approved these changes

2020-09-03 11:16 UTC, merged