Rating statistics added with logging to log file and database
ita-social-projects/GreenCity pull request #1411
Opened 2020-09-16 21:12 UTC by TarasDovganyuk

2020-09-17 06:37 UTC, antonbakalets requested changes

2020-09-17 06:37 UTC, antonbakalets commented on core/src/main/java/greencity/entity/User.java
> +    @OneToMany(mappedBy = "user")
Please add LAZY. We don't want to load all statistics when loading user.

2020-09-17 06:37 UTC, antonbakalets commented on core/src/main/java/greencity/repository/RatingStatisticsRepo.java
> +        value = "DELETE FROM rating_statistics WHERE create_date + interval '2 year' < current_date")
According to the task 2 years must be parameterized/configurable, but feel free to create a separate pull request.

2020-09-17 06:37 UTC, antonbakalets commented on core/src/main/resources/logback.xml
> +        <appender-ref ref="console" />
Have you checked that this doesn't break main logging? main logging into file?

2020-09-17 12:53 UTC, Yura09 approved these changes

2020-09-18 10:31 UTC, vorfolomey approved these changes

2020-09-18 11:59 UTC, antonbakalets approved these changes

2020-09-18 12:55 UTC, merged