UnitTest_1428
ita-social-projects/GreenCity pull request #1439
Opened 2020-09-21 14:22 UTC by forestik

2020-09-21 18:27 UTC, antonbakalets requested changes

2020-09-21 18:27 UTC, antonbakalets commented on core/src/test/java/greencity/service/impl/FactOfTheDayTranslationServiceImplTest.java
> +        MockitoAnnotations.initMocks(this);
Please see 
- changes in https://github.com/ita-social-projects/GreenCity/pull/1353/files
- conversation in https://github.com/ita-social-projects/GreenCity/pull/1353/files/fd146c507103b8713a72173d64e2c9df32da32fb#diff-b727cc1b5710fa06c4f437b8b7413278 (click on Show outdated)

You will need:
- make fields final, remove `Autowired` annotation
- replace constructor by `AllArgsConstructor` annotation
- use `InjectMocks` annotation and remove `init` method

2020-09-21 18:27 UTC, antonbakalets commented on core/src/test/java/greencity/service/impl/FactOfTheDayTranslationServiceImplTest.java
> +        factOfTheDayTranslation.builder()
What is this test checking if the result of the `build()` invocation is ignored?

2020-09-21 18:27 UTC, antonbakalets commented on core/src/test/java/greencity/service/impl/FactOfTheDayTranslationServiceImplTest.java
> +        factOfTheDayTranslation.builder()
The same here.

2020-09-21 18:27 UTC, antonbakalets commented on core/src/test/java/greencity/service/impl/FactOfTheDayTranslationServiceImplTest.java
> +                .content("Content")
The same here.

2020-09-21 18:27 UTC, antonbakalets commented on core/src/test/java/greencity/service/impl/HabitStatusCalendarServiceImplTest.java
> +        habitStatusCalendarService = new HabitStatusCalendarServiceImpl(habitStatusCalendarRepo);
The same here.

2020-09-21 18:27 UTC, antonbakalets commented on core/src/test/java/greencity/service/impl/HabitStatusServiceImplTest.java
> +        MockitoAnnotations.initMocks(this);
The same here.

2020-09-21 18:27 UTC, antonbakalets commented on core/src/test/java/greencity/service/impl/SocialNetworkImageServiceImplTest.java
> +        socialNetworkImageService= new SocialNetworkImageServiceImpl(socialNetworkImageRepo, fileService);
The same here.

2020-09-22 16:08 UTC, antonbakalets approved these changes

2020-09-22 16:58 UTC, eyouu approved these changes

2020-09-23 07:07 UTC, Yura09 approved these changes

2020-09-23 07:25 UTC, merged