RatingStatistics UI for management page added, exporter to Excel file implemented
ita-social-projects/GreenCity pull request #1478
Opened 2020-09-24 07:43 UTC by TarasDovganyuk

2020-09-24 10:08 UTC, Yura09 approved these changes

2020-09-24 11:13 UTC, antonbakalets requested changes

2020-09-24 11:13 UTC, antonbakalets commented on core/src/main/java/greencity/dto/ratingstatistics/RatingStatisticsDto.java
> +    private User user;
There will be a problem later. `RatingStatisticsDto` is a DTO from Controllers layer. `User` is an Entity from DAO layer. Please either replace by something like `String username` or introduce a kind of `UserDto`.

2020-09-24 11:13 UTC, antonbakalets commented on core/src/main/java/greencity/exporter/RatingExcelExporter.java
> +        workbook = new XSSFWorkbook();
This design is not thread save. Imagine the `export()` method is invoked from another thread.

2020-09-24 11:13 UTC, antonbakalets commented on core/src/main/java/greencity/exporter/RatingExcelExporter.java
> +        workbook.close();
`workbook` implements `AutoClosable`, so it should be closed in a `try-with-resource` block.

2020-09-24 11:13 UTC, antonbakalets commented on core/src/main/java/greencity/repository/RatingStatisticsRepo.java
> +    List<RatingStatistics> findAll();
Method `findAll()` is already available in `JpaRepository` that this interface extends, so no need to introduce it here.

2020-09-24 11:13 UTC, antonbakalets commented on core/src/main/java/greencity/exporter/RatingExcelExporter.java
> +    public void export(HttpServletResponse response) throws IOException {
Please pass as parameter only the object you really need. You need only the `OutputStream`, not the `HttpServletResponse`.

2020-09-24 11:13 UTC, antonbakalets commented on core/src/main/java/greencity/webcontroller/ManagementRatingStatisticsController.java
> +        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
`dateFormat` can be created once, as a constant or a Singleton bean.

2020-09-25 10:32 UTC, antonbakalets requested changes

2020-09-25 10:32 UTC, antonbakalets commented on core/src/main/java/greencity/exporter/RatingExcelExporter.java
> +            ex.printStackTrace();
Don't use that in real life. Replace by

`logger.error("Some Message", ex);`

2020-09-25 14:53 UTC, antonbakalets approved these changes

2020-09-25 17:35 UTC, eyouu approved these changes

2020-09-25 17:39 UTC, forestik approved these changes

2020-09-25 18:59 UTC, merged