Graphs performance update
ita-social-projects/GreenCity pull request #1481
Opened 2020-09-24 14:08 UTC by eyouu

2020-09-25 12:19 UTC, TarasDovganyuk approved these changes

2020-09-25 13:18 UTC, Yura09 approved these changes

2020-09-25 16:39 UTC, antonbakalets requested changes
As discussed this is not ready.

2020-09-27 11:12 UTC, antonbakalets approved these changes

2020-09-27 11:12 UTC, antonbakalets commented on core/src/main/java/greencity/service/impl/GraphServiceImpl.java
> +        months.forEach(month -> map.put(month, map.get(month) + 1));
Calculating COUNT or SUM in the database query would be even more performant.

2020-09-28 08:00 UTC, vorfolomey approved these changes

2020-09-28 09:14 UTC, merged