Move repository to DAO module
ita-social-projects/GreenCity pull request #1522
Opened 2020-09-29 13:48 UTC by eyouu

2020-09-29 13:59 UTC, Yura09 approved these changes

2020-09-29 15:50 UTC, vorfolomey approved these changes

2020-09-29 18:35 UTC, antonbakalets requested changes
AppConstant should definitively stay at controller (main application) level.

2020-09-29 18:35 UTC, antonbakalets commented on core/src/main/java/greencity/controller/HabitController.java
> -import greencity.dto.habitstatistic.HabitStatisticDto;
`HabitStatisticDto` should stay. The constructor that depends on entity should be replaced by mapper.

2020-09-29 18:35 UTC, antonbakalets commented on core/src/main/java/greencity/controller/HabitController.java
> -import greencity.dto.habitstatistic.HabitStatisticDto;
Most probably the same for other DTOs that are used in controllers. Only DTOs that are mapped as query result can go to dao level.

2020-09-29 18:47 UTC, antonbakalets commented
Here is the problem with this task. The only field from `AppConstant` used is `greencity.constant.AppConstant#DATE_FORMAT` But the conversion from String->LocalDateTime should happen at Controller level, preferably it should be Spring responsibility.

- Please try to change the greencity.dto.filter.FilterPlaceDto#time field type to LocalDateTime.

- if that is quite complicated we could hardcode the date format and create a separate ticket to fix it.

2020-09-30 10:54 UTC, eyouu commented
> Here is the problem with this task. The only field from `AppConstant` used is `greencity.constant.AppConstant#DATE_FORMAT` But the conversion from `String->LocalDateTime` should happen at Controller level, preferably it should be Spring responsibility.
> 
> * Please try to change the `greencity.dto.filter.FilterPlaceDto#time` field type to `LocalDateTime`.
> * if that is quite complicated we could hardcode the date format and create a separate ticket to fix it.

For out now just hardcoded the format, but I'll create a separate ticket and will do this task (as it was discussed)

2020-09-30 18:39 UTC, antonbakalets approved these changes

2020-09-30 18:49 UTC, TarasDovganyuk approved these changes

2020-10-01 09:06 UTC, merged