Remove unused imports, raname methods and use primitive boolean expre…
ita-social-projects/GreenCity pull request #1533
Opened 2020-09-30 08:34 UTC by forestik

…ssion

2020-09-30 09:55 UTC, antonbakalets requested changes

2020-09-30 09:55 UTC, antonbakalets commented on core/src/main/java/greencity/validator/TipsAndTricksDtoRequestValidator.java
> +        if ((Boolean.TRUE.equals(tagService.isValidNumOfUniqueTags(dto.getTags())))
`Boolean.TRUE.equals(x)` is actually equal to `x`, so it can be removed.

2020-09-30 09:55 UTC, antonbakalets commented on core/src/main/java/greencity/repository/AdviceTranslationRepo.java
> +    Optional<AdviceTranslation> findAdviceTranslationByLanguageCodeAndAdvice(String languageCode, String advice);
Have you checked that the generated SQL query is still the same?

2020-09-30 10:20 UTC, forestik commented on core/src/main/java/greencity/validator/TipsAndTricksDtoRequestValidator.java
> +        if ((Boolean.TRUE.equals(tagService.isValidNumOfUniqueTags(dto.getTags())))
I understand this, but the sonar gives out code smells

2020-09-30 12:08 UTC, antonbakalets commented on core/src/main/java/greencity/validator/TipsAndTricksDtoRequestValidator.java
> +        if ((Boolean.TRUE.equals(tagService.isValidNumOfUniqueTags(dto.getTags())))
I believe Sonar is trying to say that `greencity.service.impl.TagsServiceImpl#isValidNumOfUniqueTags` method return type can be changed to primitive `boolean`.

2020-09-30 12:38 UTC, forestik commented on core/src/main/java/greencity/validator/TipsAndTricksDtoRequestValidator.java
> +        if ((Boolean.TRUE.equals(tagService.isValidNumOfUniqueTags(dto.getTags())))
I thought the same and changed to a primitive, but nothing changed.
Also in the example is :
![image](https://user-images.githubusercontent.com/68025190/94685551-440ec980-0332-11eb-8506-023551d706bd.png)

2020-09-30 12:45 UTC, forestik commented on core/src/main/java/greencity/validator/TipsAndTricksDtoRequestValidator.java
> +        if ((Boolean.TRUE.equals(tagService.isValidNumOfUniqueTags(dto.getTags())))
Ок

2020-09-30 18:34 UTC, antonbakalets requested changes

2020-09-30 18:34 UTC, antonbakalets commented on core/src/main/java/greencity/validator/TipsAndTricksDtoRequestValidator.java
> +                && (!tagService.isAllTipsAndTricksValid(dto.getTags()))) {
I'm afraid the logic has change now.

2020-10-01 07:49 UTC, antonbakalets approved these changes

2020-10-01 10:35 UTC, eyouu approved these changes

2020-10-01 12:03 UTC, TarasDovganyuk approved these changes

2020-10-01 12:12 UTC, merged