issue1351_rating_statistics_filters
ita-social-projects/GreenCity pull request #1535
Opened 2020-09-30 10:43 UTC by TarasDovganyuk

2020-09-30 10:47 UTC, antonbakalets commented
Could you please provide a more descriptive, human readable title that gives the idea what it's all about?

2020-09-30 10:51 UTC, TarasDovganyuk commented
> Could you please provide a more descriptive, human readable title that gives the idea what it's all about?

Done)

2020-09-30 10:57 UTC, antonbakalets requested changes

2020-09-30 10:57 UTC, antonbakalets commented on core/src/main/java/greencity/filters/RatingStatisticsSpecification.java
> +            return allPredicates;
After this `return` other `if` statements are unreachable?

2020-09-30 10:57 UTC, antonbakalets commented on core/src/main/java/greencity/filters/RatingStatisticsSpecification.java
> +    private UserService userService;
`UserService` **will not** be reachable from DAO layer. Please replace by `UserRepo`.

2020-09-30 10:57 UTC, antonbakalets commented on core/src/main/java/greencity/webcontroller/ManagementRatingStatisticsController.java
> +        this.spec = spec;
`RatingStatisticsSpecification` must be created at Service level. A new one per each request.

2020-09-30 10:57 UTC, antonbakalets commented on core/src/main/java/greencity/webcontroller/ManagementRatingStatisticsController.java
> +        spec.setSearchCriteria(searchCriteria);
This is awful. Imagine 10 users making request simultaneously. Whos `searchCriteria` will be set into the `spec`?

2020-09-30 18:35 UTC, antonbakalets commented
> > Could you please provide a more descriptive, human readable title that gives the idea what it's all about?
> 
> Done)

You have updated the description, the title is still weird.

2020-10-01 13:49 UTC, antonbakalets approved these changes

2020-10-01 13:49 UTC, antonbakalets commented on core/src/main/resources/static/management/css/table_Modal_Pagination.css
> +/*    color: white;*/
It is better to remove now or it will stay here forever.

2020-10-01 13:49 UTC, antonbakalets commented on core/src/main/resources/templates/core/management_user_rating.html
> +        document.getElementById("searchForm").action = "/management/rating/exportFiltered";
Imagine `.submit()` will fail, the action won't be returned to previous value.
It's better to create two functions (bind them to events) each submitting to its own url.

2020-10-01 15:11 UTC, vorfolomey approved these changes

2020-10-01 15:21 UTC, merged