Management social network images
ita-social-projects/GreenCity pull request #1564
Opened 2020-10-03 07:37 UTC by forestik

2020-10-03 13:10 UTC, Yura09 approved these changes

2020-10-03 14:21 UTC, antonbakalets requested changes

2020-10-03 14:21 UTC, antonbakalets commented on core/src/main/java/greencity/service/impl/SocialNetworkImageServiceImpl.java
> +    public SocialNetworkImage findById(Long id) {
Could you please hide this method by making it private and removing from the interface. 

This way you will not expose `SocialNetworkImage` to the Controller layer. This is what we are trying to achieve in this epic about 3-layers application.

2020-10-04 04:30 UTC, antonbakalets approved these changes

2020-10-04 09:17 UTC, eyouu approved these changes

2020-10-04 09:31 UTC, merged