issue1609_spesification
ita-social-projects/GreenCity pull request #1610
Opened 2020-10-08 15:43 UTC by TarasDovganyuk

Shared methods moved to Interface

2020-10-08 16:26 UTC, antonbakalets requested changes

2020-10-08 16:26 UTC, antonbakalets commented on core/src/main/java/greencity/filters/MySpecification.java
> +public interface MySpecification<T> extends Specification<T> {
Why interface? Why is this a @Component?

What I was explaining is, for example:
- you have `RatingStatisticsRepo extends JpaSpecificationExecutor<RatingStatistics>` -> allows you to call `findAll(Specification)`
- `RatingStatisticsRepo` is an interface -> you can't add logic
- but starting from Java 8 you can add `default` methods -> put the method that converts DTO to `Specification` in the interface/repo that uses this Specification

2020-10-13 07:45 UTC, antonbakalets approved these changes

2020-10-13 08:30 UTC, forestik approved these changes

2020-10-13 08:30 UTC, eyouu approved these changes

2020-10-13 08:34 UTC, merged