Moved service to another module
ita-social-projects/GreenCity pull request #1619
Opened 2020-10-09 11:56 UTC by Yura09

2020-10-09 12:41 UTC, eyouu approved these changes

2020-10-09 12:50 UTC, antonbakalets reviewed
Please hold down with this task:

The `...ServiceImpl` and `...ServiceImplTest` should be in `service` module, not `service-api`

2020-10-09 12:50 UTC, antonbakalets commented on service-api/pom.xml
> +        <mockito-junit-jupiter.version>3.3.3</mockito-junit-jupiter.version>
Please move properties into parent pom.xml.

2020-10-09 15:14 UTC, antonbakalets requested changes

2020-10-09 15:14 UTC, antonbakalets commented on core/pom.xml
> +            <scope>runtime</scope>
Please comment this out and mark as TODO in #1618

2020-10-09 15:14 UTC, antonbakalets commented on service-api/pom.xml
> +            <groupId>org.springframework.boot</groupId>
Why do you need this? I believe you don't need the whole web, but just some of dependencies from it.

2020-10-09 15:14 UTC, antonbakalets commented on service-api/pom.xml
> +            <groupId>greencity</groupId>
This must be in Service-Impl module. The API don't based on what the implementation is done.

2020-10-09 15:14 UTC, antonbakalets commented on service-api/pom.xml
> +            <scope>runtime</scope>
Please comment this out and mark as TODO in #1618

2020-10-09 15:14 UTC, antonbakalets commented on service-api/src/main/java/greencity/constant/CacheConstants.java
> +    public static final String ALL_ACHIEVEMENTS_CACHE_NAME = "achievements_cache";
move to Impl.

2020-10-09 15:14 UTC, antonbakalets commented on service/pom.xml
> +            <scope>compile</scope>
runtime, commented and marked as TODO

2020-10-09 15:14 UTC, antonbakalets commented on service/pom.xml
> +            <artifactId>validation-api</artifactId>
Already available from Service-API pom

2020-10-10 06:06 UTC, antonbakalets approved these changes

2020-10-10 06:33 UTC, forestik approved these changes

2020-10-10 07:19 UTC, merged