Duration and complexity add
ita-social-projects/GreenCity pull request #2891
Opened 2021-06-11 11:05 UTC by DTomSawyer

Add default duration and complexity in pop up for creation new habit from admin page

2021-06-11 11:12 UTC, DanylkoMykola approved these changes

2021-06-11 11:36 UTC, ZaharVeremchuk requested changes
Close this pull request, it has not your commits too

2021-06-14 10:43 UTC, ZaharVeremchuk approved these changes

2021-06-14 12:53 UTC, NazariySt approved these changes

2021-06-14 12:55 UTC, rusanovscaia approved these changes

2021-06-14 12:56 UTC, merged