Docker Container and Integration tests for LanguageRepo
ita-social-projects/GreenCity pull request #3837
Opened 2022-02-02 20:16 UTC by Natalia1910

2022-02-04 21:22 UTC, Zingerd approved these changes

2022-02-04 21:28 UTC, VadymMakitra requested changes

2022-02-04 21:28 UTC, VadymMakitra commented on core/pom.xml
> +            <version>4.5.2</version>
Introduce it in global variable properties

2022-02-04 21:28 UTC, VadymMakitra commented on pom.xml
> +        <test.containers.version>1.15.1</test.containers.version>
Introduce it in global variable properties

2022-02-04 21:28 UTC, VadymMakitra commented on pom.xml
> +                <version>2.22.2</version>
same

2022-02-05 21:45 UTC, KuzbytMaksym approved these changes

2022-02-06 00:07 UTC, SomeOne35719 approved these changes

2022-02-06 22:11 UTC, VadymMakitra approved these changes

2022-02-06 23:22 UTC, merged