Event is active field, Delete the event - IN PROGRESS
ita-social-projects/GreenCity pull request #4720
Opened 2022-11-07 13:09 UTC by kmpol

Before the (partial - no tests) implementation:

Delete event button: no behavior

After the (partial - no tests) implementation:

Delete button deletes in two way:
-- First: If there are event attenders - soft delete (remove from view, but still available in the db)
-- Second: If there are no event attenders - hard delete (remove from db)

Before the deletion - modal asks if you are sure about the deletion.

2022-11-08 07:16 UTC, marcinkunert requested changes

2022-11-08 07:16 UTC, marcinkunert commented on core/src/main/java/greencity/webcontroller/ManagementEventsController.java
> +        @ApiIgnore Pageable pageable, EventViewDto eventViewDto, @RequestParam(required = false, name = "active", defaultValue = "false") boolean active) {
If you use defaultValue then `required = false` is not needed

2022-11-08 07:16 UTC, marcinkunert commented on core/src/main/resources/static/css/sidebar.css
> +    padding: 2rem 1rem !IMPORTANT;
I've never seen `!important` written in caps 😅

2022-11-08 07:16 UTC, marcinkunert commented on core/src/main/resources/templates/core/management_events.html
> +<!--        </div>-->
Did you comment that out on purpose? Either delete it completely or bring this back

2022-11-08 07:16 UTC, marcinkunert commented on service/src/main/java/greencity/service/EventServiceImpl.java
> +    @Transactional
If this is added on purpose, what's the benefit?

2022-11-08 07:16 UTC, marcinkunert commented on service/src/main/java/greencity/service/EventServiceImpl.java
> +                .filter(Event::getIsActive)
It is better to do filtering on the database side.

2022-11-08 07:16 UTC, marcinkunert commented on service/src/main/java/greencity/service/EventServiceImpl.java
> +        }
I'm not a fan of this approach. Consider moving the principal part into delete and update metods

2022-11-10 13:29 UTC, kmpol commented on service/src/main/java/greencity/service/EventServiceImpl.java
> +                .filter(Event::getIsActive)
Yes, but there might be in the future some functionality, which could be "filter", that shows me only active and inactive events.
For now we are getting whole db and filter inactive events out. In the future we still want whole db downloaded and just filter active out in order to show inactive ones. So we could active them back.

2022-11-10 18:56 UTC, PawelMiskowiec approved these changes

2024-04-05 14:59 UTC, closed without merging