Added likes and dislikes column to eco news management panel (#4686).
ita-social-projects/GreenCity pull request #4723
Opened 2022-11-08 08:33 UTC by lena-bykanowa

- add dislike endpoint
- list eco news likes/dislikes
- view likes/dislikes from eco news panel
- code fix

2022-11-14 14:05 UTC, PawelMiskowiec approved these changes

2022-11-14 14:05 UTC, PawelMiskowiec commented on core/src/test/java/greencity/controller/EcoNewsControllerTest.java
> +        when(userService.findByEmail(anyString())).thenReturn(userVO);
a think this belongs to given

2022-11-18 11:12 UTC, F1iper requested changes

2022-11-18 11:12 UTC, F1iper commented on core/src/main/resources/templates/core/management_eco_news.html
> +        }*/
Seems like an unnecessary comment

2022-11-19 09:53 UTC, macuzarski approved these changes

2022-11-19 10:45 UTC, lena-bykanowa commented on core/src/test/java/greencity/controller/EcoNewsControllerTest.java
> +        when(userService.findByEmail(anyString())).thenReturn(userVO);
fixed in new pr

2022-11-19 10:45 UTC, lena-bykanowa commented on core/src/main/resources/templates/core/management_eco_news.html
> +        }*/
fixed :)

2022-11-19 13:54 UTC, F1iper approved these changes

2022-11-21 08:57 UTC, merged