refactored PATCH /events/comments and PATCH /econews/comments (comment text is no longer a param)
ita-social-projects/GreenCity pull request #7125
Opened 2024-05-09 10:57 UTC by lukovskyj

# GreenCity PR

![pi1](https://github.com/ita-social-projects/GreenCity/assets/73854494/2a2a4839-0c78-454e-bd5f-7b650a1ea890)
Currently, the endpoint for updating comments for both econews and events requires comment text as a parameter.

Summary Of Changes 🔥

Refactored PATCH /events/comments and PATCH /econews/comments; now both endpoints require comment text in the request body instead of as a parameter, as it was previously. 

Issue Link 📋

https://github.com/ita-social-projects/GreenCity/issues/6833

# PR Checklist Forms

_(to be filled out by PR submitter)_
- [x ] Code is up-to-date with the `dev` branch.
- [x] You've successfully built and run the tests locally.
- [x] There are new or updated unit tests validating the change.
- [x] JIRA/ Github Issue number & title in PR title (ISSUE-XXXX: Ticket title)
- [x] This template filled (above this section).
- [x] Sonar's report does not contain bugs, vulnerabilities, security issues, code smells or duplication
- [x] `NEED_REVIEW` and `READY_FOR_REVIEW` labels are added.
- [x] All files reviewed before sending to reviewers

2024-05-20 09:54 UTC, DenysLiubchenko requested changes

2024-05-20 09:54 UTC, DenysLiubchenko commented on core/src/main/java/greencity/controller/EcoNewsCommentController.java
> +import greencity.dto.econewscomment.*;
We dont use wildcart imports

2024-05-20 09:54 UTC, DenysLiubchenko commented on service-api/src/main/java/greencity/dto/econewscomment/UpdateEcoNewsCommentDtoRequest.java
> +    public String text;
You can put these annotations on the field itself and not create a DTO for one field.

2024-05-20 09:54 UTC, DenysLiubchenko commented on service-api/src/main/java/greencity/dto/eventcomment/UpdateEventCommentDtoRequest.java
> +    private String text;
Same as with news

2024-05-20 10:54 UTC, HelenSotnik approved these changes

2024-05-21 11:23 UTC, ryhaldenys approved these changes

2024-05-22 12:18 UTC, DenysLiubchenko approved these changes

2024-05-22 12:18 UTC, merged